[package]
name = "c82"
version = "0.1.0"
authors = ["Bruce Collie <brucecollie82@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.9.0"
